### ISSUE TITLE
[ WARN] [1455207433.835350875, 923.836000000]: Assimp reports no scene in package://robotiq_85_description/meshes/robotiq_85_gripper/collision/robotiq_85_inner_knuckle_link.stl

### ISSUE THREAD

**Issue by MetaMemoryT** [StanleyInnovation/robotiq_85_gripper#4]
I think this has to do with malformed file: http://notebook.updroid.com/2016/01/04/from-solidworks-to-collada-urdf/

strange, I checked the binary file: robotiq_85_inner_knuckle_link.stl
and the word solid was not at the beginning.

it loads fine:

https://github.com/StanleyInnovation/robotiq_85_gripper/blob/master/robotiq_85_description/meshes/robotiq_85_gripper/collision/robotiq_85_inner_knuckle_link.stl

**Comment by PatrickHussey** [comment]
It's actually an issue with the length of the file path name. The 'solid' word in the header was fixed when I created them.

I'll fix it when I get a chance

**Comment by MetaMemoryT** [comment]
Thanks for the info:

I got around the problem by renaming:

robotiq_85_inner_knuckle_link.stl to robotiq_85_ikl.stl

**Comment by PatrickHussey** [comment]
Sounds good, I made sure the issue got resolved for everything by renaming 

robotiq_85_description/meshes/robotiq_85_gripper/collision/

to

robotiq_description/meshes/robotiq_85/collision/

**Comment by PatrickHussey** [comment]
fixed paths in latest checkin to get rid of this error
